import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Bell, Mail } from "lucide-react";
import { sidebarLinks } from "@/config/dashboard";
import { SearchCommand } from "@/components/search-command";
import {
  DashboardSidebar,
  MobileSheetSidebar,
} from "@/components/dashboard-sidebar";
import MaxWidthWrapper from "@/components/shared/max-width-wrapper";
import { UserAccountNav } from "@/components/user-account-nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const filteredLinks = sidebarLinks.map((section) => ({
    ...section,
  }));

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background antialiased`}
      >
        <div className="relative flex min-h-screen w-full">
          <div
            className="fixed inset-0 z-[-1] bg-cover bg-center bg-no-repeat opacity-[0.13]"
            style={{
              backgroundImage: "url('/_static/background.jpg')",
              backgroundAttachment: "fixed",
            }}
          />
          <DashboardSidebar links={filteredLinks} />

          <div className="flex flex-1 flex-col">
            <header className="sticky top-0 z-50 flex h-14 px-4 backdrop-blur-sm lg:h-[60px] xl:px-8">
              <MaxWidthWrapper className="flex max-w-7xl items-center gap-x-3 px-0">
                <MobileSheetSidebar links={filteredLinks} />

                <div className="flex w-full justify-start">
                  <SearchCommand links={filteredLinks} />
                </div>
                <div className="flex items-center space-x-3">
                  <div className="rounded-full border">
                    <Mail className="size-9 p-2 text-gray-500" />
                  </div>
                  <Bell className="size-9 rounded-full border p-2 text-gray-500" />
                  <UserAccountNav />
                </div>
              </MaxWidthWrapper>
            </header>

            <main className="flex-1 p-4 xl:px-8">
              <MaxWidthWrapper className="flex h-full max-w-7xl flex-col gap-4 px-0 lg:gap-6">
                {children}
              </MaxWidthWrapper>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
